# These are supported funding model platforms

github: kings1990 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: kings1990# Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: kings1990 # Replace with a single Ko-fi username
tidelift: maven/rap2-generator # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: rap2-generator # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: kings1990 # Replace with a single Liberapay username
issuehunt: kings1990 # Replace with a single IssueHunt username
otechie: kings1990 # Replace with a single Otechie username
custom: https://www.paypal.com/paypalme/kings9090 # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
